data:
  with_augmentation: True

  original_data_path: "/projects/dsci410_510/Levin_MAED/data/raw"
  split_data_path: "/projects/dsci410_510/Levin_MAED/data/split"

  original_data_path_aug: "/projects/dsci410_510/Levin_MAED/data/raw_aug"
  split_data_path_aug: "/projects/dsci410_510/Levin_MAED/data/split_aug"

  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  seed: 42

transforms:
  crop_size: 128

training:
  batch_size: 16
  epochs: 1
  learning_rate: 0.00025
  num_workers: 1
  early_stopping:
    min_delta: 0.0001
    patience: 10

model:
  architecture: convnext