data:
  # original_data_path: "data/raw"  # Path to original data
  original_data_path: "/projects/dsci410_510/Levin_MAED/data/raw"
  # split_data_path: "data/split"  # Path to save processed data
  split_data_path: "/projects/dsci410_510/Levin_MAED/data/split"
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  seed: 42

transforms:
  crop_size: 128

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.00025
  num_workers: 1

model:
  architecture: resnet50