data:
  original_data_path: /projects/dsci410_510/Levin_MAED/data/raw
  original_data_path_aug: /projects/dsci410_510/Levin_MAED/data/raw_aug
  seed: 42
  split_data_path: /projects/dsci410_510/Levin_MAED/data/split
  split_data_path_aug: /projects/dsci410_510/Levin_MAED/data/split_aug
  test_split: 0.15
  train_split: 0.7
  val_split: 0.15
  with_augmentation: true
image_degradation:
  darken: false
  darken_factor: 0.6
  downscale: false
  downscale_factor: 0.3
  gaussian_blur: false
  gaussian_blur_radius: 3
  gaussian_noise: false
  gaussian_noise_mean: 0
  gaussian_noise_std: 1
  haze: false
  haze_alpha: 0.8
  jpeg_compression: false
  jpeg_compression_quality: 1
model:
  architecture: convnext
  # checkpoint_path: ./checkpoints/convnext-epoch=40-loss/val=0.21.ckpt
  # checkpoint_path: /projects/dsci410_510/Levin_MAED/val=0.21.ckpt
  # checkpoint_path: /projects/dsci410_510/Levin_MAED/checkpoint.ckpt
  # checkpoint_path: /projects/dsci410_510/Levin_MAED/checkpoints/val=0.21.ckpt
  checkpoint_path: /projects/dsci410_510/Levin_MAED/convnext-epoch=40-loss/val=0.21.ckpt
training:
  batch_size: 32
  early_stopping:
    min_delta: 0.0001
    patience: 10
  epochs: 100
  learning_rate: 0.00075
  num_workers: 1
transforms:
  crop_size: 256
  mean:
  - 0.4656177759170532
  - 0.47914525866508484
  - 0.4972120523452759
  std:
  - 0.22458378970623016
  - 0.22613878548145294
  - 0.23085346817970276
