data:
  original_data_path: "data/raw"  # Path to original data
  split_data_path: "data/split"  # Path to save processed data
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  seed: 42

transforms:
  crop_size: 128

training:
  batch_size: 16
  epochs: 20
  learning_rate: 0.001
  num_workers: 7

model:
  architecture: resnet50